---

- name: Import setup tasks
  import_tasks: setup.yml
  tags:
    - postfix

- name: Import SASL tasks
  import_tasks: sasl.yml
  when: postfix_sasl_auth_enable
  tags:
    - postfix
    - sasl

- name: Import vimbadmin tasks
  import_tasks: vimbadmin.yml
  when: postfix_with_vimbadmin
  tags:
    - postfix
