---
- name: Converge
  hosts: all
  remote_user: root

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      changed_when: false

  roles:
    - role: alphanodes.postfix
